name: Generate Release Notes

on:
  push:
    tags:
      - "v*"     # Runs when you push tags like v1.0, v2.1.3, etc.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post summary
        run: |
          echo "## Release Notes Workflow" >> $GITHUB_STEP_SUMMARY
          echo "Tag pushed: $GITHUB_REF_NAME" >> $GITHUB_STEP_SUMMARY
          echo "Automatic release notes generated successfully!" >> $GITHUB_STEP_SUMMARY
